apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: store-front
  namespace: default
spec:
  interval: 1m
  releaseName: store-front
  chart:
    spec:
      chart: store-front
      version: "0.1.0"
      sourceRef:
        kind: HelmRepository
        name: online-store-repo
        namespace: flux-system